server {
   listen 0.0.0.0:8080;
   listen [::]:8080;
   server_name localhost;

   # Assurez-vous que c'est le répertoire de sortie de la build Angular
   root /app; 
   index index.html; # index.htm est rarement utilisé pour Angular

   # 1. Gestion du Service Worker et de la configuration PWA
   # Ces fichiers DOIVENT ÊTRE DÉLIVRÉS avec "no-cache" pour permettre au Service Worker 
   # d'identifier les nouvelles versions de l'application et de mettre à jour le cache.
   location ~* (ngsw-worker.js|ngsw.json|manifest.webmanifest) {
      add_header Cache-Control "no-cache, no-store, must-revalidate";
      # 'expires 0' est un raccourci pour Pragma: no-cache et Expires: 0.
      expires 0;
   }

   # 2. Cache agressif pour les assets statiques (JS, CSS, images)
   # Les fichiers de build Angular (ex: main.f34ffc4c.js) contiennent un hash 
   # dans leur nom. Le Service Worker se charge du cache côté client, mais 
   # un cache Nginx à long terme est sûr car le nom de fichier changera à chaque build.
   location ~* \.(js|css|jpg|jpeg|gif|png|ico|woff2|ttf|svg|eot)$ {
      # Cache de 30 jours, c'est agressif et recommandé pour les fichiers hashés
      expires 30d; 
      add_header Cache-Control "public, immutable";
   }

   # 3. Gestion de index.html
   # Le fichier index.html est le point d'entrée, il ne devrait pas être mis en cache 
   # longtemps car il est mis à jour à chaque nouvelle version.
   location = /index.html {
      expires 1h; # Un cache court de 1 heure est suffisant
      add_header Cache-Control "public, must-revalidate";
   }

   # 4. Gestion du routage Angular (Single Page Application - SPA)
   # Tente de servir le fichier demandé, sinon renvoie index.html 
   # pour que le router Angular prenne la main.
   location / {
      try_files $uri $uri/ /index.html;
   }

   proxy_connect_timeout 60s; # Temps maximum pour établir la connexion
   proxy_send_timeout 60s;    # Temps maximum pour transmettre la requête au serveur amont
   proxy_read_timeout 60s;     # Temps maximum pour recevoir la réponse du serveur amont
   
   # Configuration Gzip (recommandée)
   gzip on;
   gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;
   gzip_vary on;
   gzip_min_length 1000;
}
