server {
   listen 0.0.0.0:8080;
   listen [::]:8080;
   server_name localhost;
   access_log    off;

   root /app;
   index index.htm index.html;

   location / {
      try_files $uri $uri/ /index.html;
   }
}
