import { Component, OnDestroy } from "@angular/core";
import { ButtonBackComponent } from "../../design-system/button-back/button-back.component";
import { FormsModule } from "@angular/forms";

const PASSWORD_STRENGTH_CONFIG = [
   // --- 4 caractères ---
   // Tous types (impossible, mais pour l'exemple de structure)
   {
      minLength: 4,
      hasUpper: true,
      hasLower: true,
      hasNumber: true,
      hasSpecial: true,
      category: "immédiat",
      message: "Immédiatement craqué (trop court)",
   },
   // Maj+min+nombre
   {
      minLength: 4,
      hasUpper: true,
      hasLower: true,
      hasNumber: true,
      hasSpecial: false,
      category: "immédiat",
      message: "Immédiatement craqué (trop court)",
   },
   // Maj+min
   {
      minLength: 4,
      hasUpper: true,
      hasLower: true,
      hasNumber: false,
      hasSpecial: false,
      category: "immédiat",
      message: "Immédiatement craqué (trop court)",
   },
   // Min+nombre
   {
      minLength: 4,
      hasUpper: false,
      hasLower: true,
      hasNumber: true,
      hasSpecial: false,
      category: "immédiat",
      message: "Immédiatement craqué (trop court)",
   },
   // Maj+nombre
   {
      minLength: 4,
      hasUpper: true,
      hasLower: false,
      hasNumber: true,
      hasSpecial: false,
      category: "immédiat",
      message: "Immédiatement craqué (trop court)",
   },
   // Maj seul
   {
      minLength: 4,
      hasUpper: true,
      hasLower: false,
      hasNumber: false,
      hasSpecial: false,
      category: "immédiat",
      message: "Immédiatement craqué (trop court)",
   },
   // Min seul
   {
      minLength: 4,
      hasUpper: false,
      hasLower: true,
      hasNumber: false,
      hasSpecial: false,
      category: "immédiat",
      message: "Immédiatement craqué (trop court)",
   },
   // Nombre seul
   {
      minLength: 4,
      hasUpper: false,
      hasLower: false,
      hasNumber: true,
      hasSpecial: false,
      category: "immédiat",
      message: "Immédiatement craqué (trop court)",
   },
   // --- 5 caractères ---
   {
      minLength: 5,
      hasUpper: true,
      hasLower: true,
      hasNumber: true,
      hasSpecial: true,
      category: "rapide",
      message: "Rapide à craquer (4 secondes)",
   },
   {
      minLength: 5,
      hasUpper: true,
      hasLower: true,
      hasNumber: true,
      hasSpecial: false,
      category: "rapide",
      message: "Rapide à craquer (2 minutes)",
   },
   {
      minLength: 5,
      hasUpper: true,
      hasLower: true,
      hasNumber: false,
      hasSpecial: false,
      category: "rapide",
      message: "Rapide à craquer (57 minutes)",
   },
   {
      minLength: 5,
      hasUpper: false,
      hasLower: true,
      hasNumber: true,
      hasSpecial: false,
      category: "immédiat",
      message: "Immédiatement craqué (trop court)",
   },
   {
      minLength: 5,
      hasUpper: true,
      hasLower: false,
      hasNumber: true,
      hasSpecial: false,
      category: "immédiat",
      message: "Immédiatement craqué (trop court)",
   },
   {
      minLength: 5,
      hasUpper: true,
      hasLower: false,
      hasNumber: false,
      hasSpecial: false,
      category: "immédiat",
      message: "Immédiatement craqué (trop court)",
   },
   {
      minLength: 5,
      hasUpper: false,
      hasLower: true,
      hasNumber: false,
      hasSpecial: false,
      category: "immédiat",
      message: "Immédiatement craqué (trop court)",
   },
   {
      minLength: 5,
      hasUpper: false,
      hasLower: false,
      hasNumber: true,
      hasSpecial: false,
      category: "immédiat",
      message: "Immédiatement craqué (trop court)",
   },
   // --- 6 caractères ---
   {
      minLength: 6,
      hasUpper: true,
      hasLower: true,
      hasNumber: true,
      hasSpecial: true,
      category: "rapide",
      message: "Rapide à craquer (3 minutes)",
   },
   {
      minLength: 6,
      hasUpper: true,
      hasLower: true,
      hasNumber: true,
      hasSpecial: false,
      category: "rapide",
      message: "Rapide à craquer (2 heures)",
   },
   {
      minLength: 6,
      hasUpper: true,
      hasLower: true,
      hasNumber: false,
      hasSpecial: false,
      category: "rapide",
      message: "Rapide à craquer (2 jours)",
   },
   {
      minLength: 6,
      hasUpper: false,
      hasLower: true,
      hasNumber: true,
      hasSpecial: false,
      category: "immédiat",
      message: "Immédiatement craqué (trop court)",
   },
   {
      minLength: 6,
      hasUpper: true,
      hasLower: false,
      hasNumber: true,
      hasSpecial: false,
      category: "immédiat",
      message: "Immédiatement craqué (trop court)",
   },
   {
      minLength: 6,
      hasUpper: true,
      hasLower: false,
      hasNumber: false,
      hasSpecial: false,
      category: "immédiat",
      message: "Immédiatement craqué (trop court)",
   },
   {
      minLength: 6,
      hasUpper: false,
      hasLower: true,
      hasNumber: false,
      hasSpecial: false,
      category: "immédiat",
      message: "Immédiatement craqué (trop court)",
   },
   {
      minLength: 6,
      hasUpper: false,
      hasLower: false,
      hasNumber: true,
      hasSpecial: false,
      category: "immédiat",
      message: "Immédiatement craqué (trop court)",
   },
   // --- 7 caractères ---
   {
      minLength: 7,
      hasUpper: true,
      hasLower: true,
      hasNumber: true,
      hasSpecial: true,
      category: "rapide",
      message: "Rapide à craquer (5 heures)",
   },
   {
      minLength: 7,
      hasUpper: true,
      hasLower: true,
      hasNumber: true,
      hasSpecial: false,
      category: "rapide",
      message: "Rapide à craquer (2 jours)",
   },
   {
      minLength: 7,
      hasUpper: false,
      hasLower: true,
      hasNumber: true,
      hasSpecial: false,
      category: "immédiat",
      message: "Immédiatement craqué (trop court)",
   },
   {
      minLength: 7,
      hasUpper: true,
      hasLower: false,
      hasNumber: true,
      hasSpecial: false,
      category: "immédiat",
      message: "Immédiatement craqué (trop court)",
   },
   {
      minLength: 7,
      hasUpper: true,
      hasLower: false,
      hasNumber: false,
      hasSpecial: false,
      category: "immédiat",
      message: "Immédiatement craqué (trop court)",
   },
   {
      minLength: 7,
      hasUpper: false,
      hasLower: true,
      hasNumber: false,
      hasSpecial: false,
      category: "immédiat",
      message: "Immédiatement craqué (trop court)",
   },
   {
      minLength: 7,
      hasUpper: false,
      hasLower: false,
      hasNumber: true,
      hasSpecial: false,
      category: "immédiat",
      message: "Immédiatement craqué (trop court)",
   },
   // --- 8 caractères ---
   {
      minLength: 8,
      hasUpper: true,
      hasLower: true,
      hasNumber: true,
      hasSpecial: true,
      category: "correct",
      message: "Correct (8 jours)",
   },
   {
      minLength: 8,
      hasUpper: true,
      hasLower: true,
      hasNumber: true,
      hasSpecial: false,
      category: "correct",
      message: "Correct (2 mois)",
   },
   {
      minLength: 8,
      hasUpper: false,
      hasLower: true,
      hasNumber: true,
      hasSpecial: false,
      category: "immédiat",
      message: "Immédiatement craqué (trop court)",
   },
   {
      minLength: 8,
      hasUpper: true,
      hasLower: false,
      hasNumber: true,
      hasSpecial: false,
      category: "immédiat",
      message: "Immédiatement craqué (trop court)",
   },
   {
      minLength: 8,
      hasUpper: true,
      hasLower: false,
      hasNumber: false,
      hasSpecial: false,
      category: "immédiat",
      message: "Immédiatement craqué (trop court)",
   },
   {
      minLength: 8,
      hasUpper: false,
      hasLower: true,
      hasNumber: false,
      hasSpecial: false,
      category: "immédiat",
      message: "Immédiatement craqué (trop court)",
   },
   {
      minLength: 8,
      hasUpper: false,
      hasLower: false,
      hasNumber: true,
      hasSpecial: false,
      category: "immédiat",
      message: "Immédiatement craqué (trop court)",
   },
   // --- 9 caractères ---
   {
      minLength: 9,
      hasUpper: true,
      hasLower: true,
      hasNumber: true,
      hasSpecial: true,
      category: "correct",
      message: "Correct (3 ans)",
   },
   {
      minLength: 9,
      hasUpper: true,
      hasLower: true,
      hasNumber: true,
      hasSpecial: false,
      category: "correct",
      message: "Correct (11 ans)",
   },
   {
      minLength: 9,
      hasUpper: false,
      hasLower: true,
      hasNumber: true,
      hasSpecial: false,
      category: "immédiat",
      message: "Immédiatement craqué (trop court)",
   },
   {
      minLength: 9,
      hasUpper: true,
      hasLower: false,
      hasNumber: true,
      hasSpecial: false,
      category: "immédiat",
      message: "Immédiatement craqué (trop court)",
   },
   {
      minLength: 9,
      hasUpper: true,
      hasLower: false,
      hasNumber: false,
      hasSpecial: false,
      category: "immédiat",
      message: "Immédiatement craqué (trop court)",
   },
   {
      minLength: 9,
      hasUpper: false,
      hasLower: true,
      hasNumber: false,
      hasSpecial: false,
      category: "immédiat",
      message: "Immédiatement craqué (trop court)",
   },
   {
      minLength: 9,
      hasUpper: false,
      hasLower: false,
      hasNumber: true,
      hasSpecial: false,
      category: "immédiat",
      message: "Immédiatement craqué (trop court)",
   },
   // --- 10 caractères ---
   {
      minLength: 10,
      hasUpper: true,
      hasLower: true,
      hasNumber: true,
      hasSpecial: true,
      category: "correct",
      message: "Correct (226 ans)",
   },
   {
      minLength: 10,
      hasUpper: true,
      hasLower: true,
      hasNumber: true,
      hasSpecial: false,
      category: "correct",
      message: "Correct (600 ans)",
   },
   {
      minLength: 10,
      hasUpper: false,
      hasLower: true,
      hasNumber: true,
      hasSpecial: false,
      category: "immédiat",
      message: "Immédiatement craqué (trop court)",
   },
   {
      minLength: 10,
      hasUpper: true,
      hasLower: false,
      hasNumber: true,
      hasSpecial: false,
      category: "immédiat",
      message: "Immédiatement craqué (trop court)",
   },
   {
      minLength: 10,
      hasUpper: true,
      hasLower: false,
      hasNumber: false,
      hasSpecial: false,
      category: "immédiat",
      message: "Immédiatement craqué (trop court)",
   },
   {
      minLength: 10,
      hasUpper: false,
      hasLower: true,
      hasNumber: false,
      hasSpecial: false,
      category: "immédiat",
      message: "Immédiatement craqué (trop court)",
   },
   {
      minLength: 10,
      hasUpper: false,
      hasLower: false,
      hasNumber: true,
      hasSpecial: false,
      category: "immédiat",
      message: "Immédiatement craqué (trop court)",
   },
   // --- 11 caractères ---
   {
      minLength: 11,
      hasUpper: true,
      hasLower: true,
      hasNumber: true,
      hasSpecial: true,
      category: "super",
      message: "Super (34 000 ans)",
   },
   {
      minLength: 11,
      hasUpper: true,
      hasLower: true,
      hasNumber: true,
      hasSpecial: false,
      category: "super",
      message: "Super (3 ans)",
   },
   {
      minLength: 11,
      hasUpper: false,
      hasLower: true,
      hasNumber: true,
      hasSpecial: false,
      category: "immédiat",
      message: "Immédiatement craqué (trop court)",
   },
   {
      minLength: 11,
      hasUpper: true,
      hasLower: false,
      hasNumber: true,
      hasSpecial: false,
      category: "immédiat",
      message: "Immédiatement craqué (trop court)",
   },
   {
      minLength: 11,
      hasUpper: true,
      hasLower: false,
      hasNumber: false,
      hasSpecial: false,
      category: "immédiat",
      message: "Immédiatement craqué (trop court)",
   },
   {
      minLength: 11,
      hasUpper: false,
      hasLower: true,
      hasNumber: false,
      hasSpecial: false,
      category: "immédiat",
      message: "Immédiatement craqué (trop court)",
   },
   {
      minLength: 11,
      hasUpper: false,
      hasLower: false,
      hasNumber: true,
      hasSpecial: false,
      category: "immédiat",
      message: "Immédiatement craqué (trop court)",
   },
   // --- 12 caractères ---
   {
      minLength: 12,
      hasUpper: true,
      hasLower: true,
      hasNumber: true,
      hasSpecial: true,
      category: "super",
      message: "Super (2 millions d'années)",
   },
   {
      minLength: 12,
      hasUpper: true,
      hasLower: true,
      hasNumber: true,
      hasSpecial: false,
      category: "super",
      message: "Super (28 ans)",
   },
   {
      minLength: 12,
      hasUpper: false,
      hasLower: true,
      hasNumber: true,
      hasSpecial: false,
      category: "immédiat",
      message: "Immédiatement craqué (trop court)",
   },
   {
      minLength: 12,
      hasUpper: true,
      hasLower: false,
      hasNumber: true,
      hasSpecial: false,
      category: "immédiat",
      message: "Immédiatement craqué (trop court)",
   },
   {
      minLength: 12,
      hasUpper: true,
      hasLower: false,
      hasNumber: false,
      hasSpecial: false,
      category: "immédiat",
      message: "Immédiatement craqué (trop court)",
   },
   {
      minLength: 12,
      hasUpper: false,
      hasLower: true,
      hasNumber: false,
      hasSpecial: false,
      category: "immédiat",
      message: "Immédiatement craqué (trop court)",
   },
   {
      minLength: 12,
      hasUpper: false,
      hasLower: false,
      hasNumber: true,
      hasSpecial: false,
      category: "immédiat",
      message: "Immédiatement craqué (trop court)",
   },
   // --- 13 caractères ---
   {
      minLength: 13,
      hasUpper: true,
      hasLower: true,
      hasNumber: true,
      hasSpecial: true,
      category: "super",
      message: "Super (123 millions d'années)",
   },
   {
      minLength: 13,
      hasUpper: true,
      hasLower: true,
      hasNumber: true,
      hasSpecial: false,
      category: "super",
      message: "Correct (284 ans)",
   },
   {
      minLength: 13,
      hasUpper: false,
      hasLower: true,
      hasNumber: true,
      hasSpecial: false,
      category: "immédiat",
      message: "Immédiatement craqué (trop court)",
   },
   {
      minLength: 13,
      hasUpper: true,
      hasLower: false,
      hasNumber: true,
      hasSpecial: false,
      category: "immédiat",
      message: "Immédiatement craqué (trop court)",
   },
   {
      minLength: 13,
      hasUpper: true,
      hasLower: false,
      hasNumber: false,
      hasSpecial: false,
      category: "immédiat",
      message: "Immédiatement craqué (trop court)",
   },
   {
      minLength: 13,
      hasUpper: false,
      hasLower: true,
      hasNumber: false,
      hasSpecial: false,
      category: "immédiat",
      message: "Immédiatement craqué (trop court)",
   },
   {
      minLength: 13,
      hasUpper: false,
      hasLower: false,
      hasNumber: true,
      hasSpecial: false,
      category: "immédiat",
      message: "Immédiatement craqué (trop court)",
   },
   // --- 14 caractères ---
   {
      minLength: 14,
      hasUpper: true,
      hasLower: true,
      hasNumber: true,
      hasSpecial: true,
      category: "super",
      message: "Super (7 milliards d'années)",
   },
   {
      minLength: 14,
      hasUpper: true,
      hasLower: true,
      hasNumber: true,
      hasSpecial: false,
      category: "super",
      message: "Correct (2 000 ans)",
   },
   {
      minLength: 14,
      hasUpper: false,
      hasLower: true,
      hasNumber: true,
      hasSpecial: false,
      category: "immédiat",
      message: "Immédiatement craqué (trop court)",
   },
   {
      minLength: 14,
      hasUpper: true,
      hasLower: false,
      hasNumber: true,
      hasSpecial: false,
      category: "immédiat",
      message: "Immédiatement craqué (trop court)",
   },
   {
      minLength: 14,
      hasUpper: true,
      hasLower: false,
      hasNumber: false,
      hasSpecial: false,
      category: "immédiat",
      message: "Immédiatement craqué (trop court)",
   },
   {
      minLength: 14,
      hasUpper: false,
      hasLower: true,
      hasNumber: false,
      hasSpecial: false,
      category: "immédiat",
      message: "Immédiatement craqué (trop court)",
   },
   {
      minLength: 14,
      hasUpper: false,
      hasLower: false,
      hasNumber: true,
      hasSpecial: false,
      category: "immédiat",
      message: "Immédiatement craqué (trop court)",
   },
   // --- 15 caractères ---
   {
      minLength: 15,
      hasUpper: true,
      hasLower: true,
      hasNumber: true,
      hasSpecial: true,
      category: "super",
      message: "Super (400 milliards d'années)",
   },
   {
      minLength: 15,
      hasUpper: true,
      hasLower: true,
      hasNumber: true,
      hasSpecial: false,
      category: "super",
      message: "Correct (28 000 ans)",
   },
   {
      minLength: 15,
      hasUpper: false,
      hasLower: true,
      hasNumber: true,
      hasSpecial: false,
      category: "immédiat",
      message: "Immédiatement craqué (trop court)",
   },
   {
      minLength: 15,
      hasUpper: true,
      hasLower: false,
      hasNumber: true,
      hasSpecial: false,
      category: "immédiat",
      message: "Immédiatement craqué (trop court)",
   },
   {
      minLength: 15,
      hasUpper: true,
      hasLower: false,
      hasNumber: false,
      hasSpecial: false,
      category: "immédiat",
      message: "Immédiatement craqué (trop court)",
   },
   {
      minLength: 15,
      hasUpper: false,
      hasLower: true,
      hasNumber: false,
      hasSpecial: false,
      category: "immédiat",
      message: "Immédiatement craqué (trop court)",
   },
   {
      minLength: 15,
      hasUpper: false,
      hasLower: false,
      hasNumber: true,
      hasSpecial: false,
      category: "immédiat",
      message: "Immédiatement craqué (trop court)",
   },
   // --- 16 caractères ---
   {
      minLength: 16,
      hasUpper: true,
      hasLower: true,
      hasNumber: true,
      hasSpecial: true,
      category: "super",
      message: "Super (24 billions d'années)",
   },
   {
      minLength: 16,
      hasUpper: true,
      hasLower: true,
      hasNumber: true,
      hasSpecial: false,
      category: "super",
      message: "Correct (284 000 ans)",
   },
   {
      minLength: 16,
      hasUpper: false,
      hasLower: true,
      hasNumber: true,
      hasSpecial: false,
      category: "immédiat",
      message: "Immédiatement craqué (trop court)",
   },
   {
      minLength: 16,
      hasUpper: true,
      hasLower: false,
      hasNumber: true,
      hasSpecial: false,
      category: "immédiat",
      message: "Immédiatement craqué (trop court)",
   },
   {
      minLength: 16,
      hasUpper: true,
      hasLower: false,
      hasNumber: false,
      hasSpecial: false,
      category: "immédiat",
      message: "Immédiatement craqué (trop court)",
   },
   {
      minLength: 16,
      hasUpper: false,
      hasLower: true,
      hasNumber: false,
      hasSpecial: false,
      category: "immédiat",
      message: "Immédiatement craqué (trop court)",
   },
   {
      minLength: 16,
      hasUpper: false,
      hasLower: false,
      hasNumber: true,
      hasSpecial: false,
      category: "immédiat",
      message: "Immédiatement craqué (trop court)",
   },
   // --- 17 caractères ---
   {
      minLength: 17,
      hasUpper: true,
      hasLower: true,
      hasNumber: true,
      hasSpecial: true,
      category: "super",
      message: "Super (1,4 billiard d'années)",
   },
   {
      minLength: 17,
      hasUpper: true,
      hasLower: true,
      hasNumber: true,
      hasSpecial: false,
      category: "super",
      message: "Super (284 000 ans)",
   },
   {
      minLength: 17,
      hasUpper: false,
      hasLower: true,
      hasNumber: true,
      hasSpecial: false,
      category: "immédiat",
      message: "Immédiatement craqué (trop court)",
   },
   {
      minLength: 17,
      hasUpper: true,
      hasLower: false,
      hasNumber: true,
      hasSpecial: false,
      category: "immédiat",
      message: "Immédiatement craqué (trop court)",
   },
   {
      minLength: 17,
      hasUpper: true,
      hasLower: false,
      hasNumber: false,
      hasSpecial: false,
      category: "immédiat",
      message: "Immédiatement craqué (trop court)",
   },
   {
      minLength: 17,
      hasUpper: false,
      hasLower: true,
      hasNumber: false,
      hasSpecial: false,
      category: "immédiat",
      message: "Immédiatement craqué (trop court)",
   },
   {
      minLength: 17,
      hasUpper: false,
      hasLower: false,
      hasNumber: true,
      hasSpecial: false,
      category: "immédiat",
      message: "Immédiatement craqué (trop court)",
   },
   // --- 18 caractères ---
   {
      minLength: 18,
      hasUpper: true,
      hasLower: true,
      hasNumber: true,
      hasSpecial: true,
      category: "super",
      message: "Super (87 billiards d'années)",
   },
   {
      minLength: 18,
      hasUpper: true,
      hasLower: true,
      hasNumber: true,
      hasSpecial: false,
      category: "super",
      message: "Super (284 000 ans)",
   },
   {
      minLength: 18,
      hasUpper: false,
      hasLower: true,
      hasNumber: true,
      hasSpecial: false,
      category: "immédiat",
      message: "Immédiatement craqué (trop court)",
   },
   {
      minLength: 18,
      hasUpper: true,
      hasLower: false,
      hasNumber: true,
      hasSpecial: false,
      category: "immédiat",
      message: "Immédiatement craqué (trop court)",
   },
   {
      minLength: 18,
      hasUpper: true,
      hasLower: false,
      hasNumber: false,
      hasSpecial: false,
      category: "immédiat",
      message: "Immédiatement craqué (trop court)",
   },
   {
      minLength: 18,
      hasUpper: false,
      hasLower: true,
      hasNumber: false,
      hasSpecial: false,
      category: "immédiat",
      message: "Immédiatement craqué (trop court)",
   },
   {
      minLength: 18,
      hasUpper: false,
      hasLower: false,
      hasNumber: true,
      hasSpecial: false,
      category: "immédiat",
      message: "Immédiatement craqué (trop court)",
   },
   // 19 chiffres seuls et plus
   {
      minLength: 19,
      hasUpper: false,
      hasLower: false,
      hasNumber: true,
      hasSpecial: false,
      category: "super",
      message: "Super (plus de 284 000 ans)",
   },
   // 19 lettres minuscules seules et plus
   {
      minLength: 19,
      hasUpper: false,
      hasLower: true,
      hasNumber: false,
      hasSpecial: false,
      category: "super",
      message: "Super (plus de 8 billions d'années)",
   },
   // 19 lettres majuscules et minuscules seules et plus
   {
      minLength: 19,
      hasUpper: true,
      hasLower: true,
      hasNumber: false,
      hasSpecial: false,
      category: "super",
      message: "Super (plus de 2 trillions d'années)",
   },
   // 19 lettres majuscules, minuscules et chiffres (sans symboles) et plus
   {
      minLength: 19,
      hasUpper: true,
      hasLower: true,
      hasNumber: true,
      hasSpecial: false,
      category: "super",
      message: "Super (plus de 87 billiards d'années)",
   },
   // 19 lettres (majuscules ou minuscules) et chiffres (sans symboles) et plus
   {
      minLength: 19,
      hasUpper: true,
      hasLower: false,
      hasNumber: true,
      hasSpecial: false,
      category: "jaune",
      message: "Super (plus de 284 000 ans)",
   },
   {
      minLength: 19,
      hasUpper: false,
      hasLower: true,
      hasNumber: true,
      hasSpecial: false,
      category: "jaune",
      message: "Super (plus de 284 000 ans)",
   },
   // 19 lettres majuscules, minuscules, chiffres et caractères spéciaux et plus
   {
      minLength: 19,
      hasUpper: true,
      hasLower: true,
      hasNumber: true,
      hasSpecial: true,
      category: "super",
      message: "Super (plus de 144 billiards d'années)",
   },
];

function getPasswordCategory(password: string): {
   category: string;
   message: string;
} {
   if (/^(.)\1+$/.test(password)) {
      return {
         category: "immédiat",
         message: "Immédiatement craqué (caractère unique répété)",
      };
   }
   const hasUpper = /[A-Z]/.test(password);
   const hasLower = /[a-z]/.test(password);
   const hasNumber = /[0-9]/.test(password);
   const hasSpecial = /[^a-zA-Z0-9]/.test(password); // Tous les caractères spéciaux
   const length = password.length;

   // On cherche la règle qui correspond exactement à la composition
   for (const rule of PASSWORD_STRENGTH_CONFIG) {
      if (
         length >= rule.minLength &&
         rule.hasUpper === hasUpper &&
         rule.hasLower === hasLower &&
         rule.hasNumber === hasNumber &&
         rule.hasSpecial === hasSpecial
      ) {
         return { category: rule.category, message: rule.message };
      }
   }
   // Par défaut, si rien ne correspond
   return { category: "immédiat", message: "Immédiatement craqué" };
}

@Component({
   selector: "app-password-check",
   imports: [ButtonBackComponent, FormsModule],
   templateUrl: "./password-check.component.html",
   styleUrl: "./password-check.component.scss",
})
export class PasswordCheckComponent implements OnDestroy {
   password: string = "";
   result: string = "";
   category: string = "";
   message: string = "";

   // Suivi de chaque critère pour affichage des icônes
   criteria = [
      { name: "Au moins 8 caractères", valid: false },
      { name: "Une majuscule", valid: false },
      { name: "Une minuscule", valid: false },
      { name: "Un chiffre", valid: false },
      { name: "Un caractère spécial", valid: false },
   ];

   checkPassword() {
      this.criteria[0].valid = this.password.length >= 8;
      this.criteria[1].valid = /[A-Z]/.test(this.password);
      this.criteria[2].valid = /[a-z]/.test(this.password);
      this.criteria[3].valid = /[0-9]/.test(this.password);
      this.criteria[4].valid = /[^A-Za-z0-9]/.test(this.password);

      // Appelle aussi la logique avancée si tu veux le message global
      const evaluation = getPasswordCategory(this.password);
      this.category = evaluation.category;
      this.message = evaluation.message;
      this.result = `Catégorie : ${this.category}`;
   }

   ngOnDestroy() {
      this.password = "";
   }
}
