export enum ComponentType {
   PAGE_1 = "PAGE_1",
   PAGE_2 = "PAGE_2",
   PAGE_3 = "PAGE_3",
   PAGE_4 = "PAGE_4",
   PAGE_5 = "PAGE_5",
   CARD_1 = "CARD_1",
   CARD_2 = "CARD_2",
   CARD_3 = "CARD_3",
   CARD_4 = "CARD_4",
   CARD_5 = "CARD_5",
   CARD_6 = "CARD_6",
   CARD_7 = "CARD_7",
   CARD_8 = "CARD_8",
   CARD_9 = "CARD_9",
   CARD_10 = "CARD_10",
   CARD_11 = "CARD_11",
   TILE_CALL = "TILE_CALL",
   TILE_MESSAGE = "TILE_MESSAGE",
   ENRICHED_LINK = "ENRICHED_LINK",
   DIVIDER = "DIVIDER",
}
