export enum CountryRegion {
   FR = "France",
   BEFR = "Belgique",
   BENL = "België",
   IE = "Éire",
   SK = "Slovensko",
   SE = "Sverige",
   HU = "Magyarország",
   GR = "Ελλάδα",
   DK = "Danmark",
   PL = "Polska",
   PT = "Portugal",
   ES = "España",
   CT = "Catalunya",
   LU = "Lëtzebuerg",
   DE = "Deutschland",
   XX = "International",
}
